SELECT 	ab.DEAL_TRACKING_NUM||'_'||ab.INS_NUM||'_'||d.PARAM_SEQ_NUM||'_'||d.PROFILE_SEQ_NUM 	AS DEAL_ATTRIBUTES_NK
	,tstd.LOC_START_DATE_TIME 						as DELIVERY_INTERVAL_START_DATE
	,tstd.LOC_START_DATE_TIME				as DELIVERY_INTERVAL_START_TIME
	,tstd.LOC_END_DATE_TIME 						as DELIVERY_INTERVAL_END_DATE
	,tstd.LOC_END_DATE_TIME				as DELIVERY_INTERVAL_END_TIME
	,(tstd.LOC_END_DATE_TIME-tstd.LOC_START_DATE_TIME)*24*60 			as DELIVERY_INTERVAL_DURATION
	,CASE WHEN tstd.PRICE = '0' THEN d.rate ELSE tstd.PRICE END	 							as DELIVERY_INTERVAL_PRICE
	,tstd.schedule_rate								as DELIVERY_INTERVAL_QTY
	,pw.product_name 						as DELIVERY_INTERVAL_TYPE
    ,AB.input_date as source_last_update
FROM 	AB_TRAN ab
 join INSTRUMENTS b 
on ab.ins_type = b.id_number
 join INS_PARAMETER f 
on ab.ins_num = f.ins_num
 join PROFILE d 
on f.param_seq_num = d.param_seq_num and f.ins_num = d.ins_num
 LEFT JOIN 	TRAN_SCHEDULE_DETAILS tsd
ON 	ab.TRAN_NUM=tsd.TRAN_NUM and f.param_seq_num = tsd.param_seq_num and d.profile_seq_num = tsd.profile_seq_num
 LEFT JOIN 	TRAN_SCHEDULE_TIME_DETAILS tstd
ON 	tsd.SCHEDULE_ID = tstd.SCHEDULE_ID 
LEFT JOIN 	(
			SELECT 	DISTINCT AB.INS_NUM,
				DECODE(PPH.PRODUCT_NAME, NULL, H.PRODUCT_NAME, PPH.PRODUCT_NAME) PRODUCT_NAME
			FROM 	AB_TRAN AB
			LEFT JOIN 	PWR_PHYS_PARAM PPP 
			ON 	PPP.INS_NUM = AB.INS_NUM
			LEFT JOIN 	PWR_PRODUCT_HEADER PPH 
			ON 	PPH.PRODUCT_ID = PPP.PRODUCT
			LEFT JOIN 	PWR_PHYS_RESET R 
			ON 	R.INS_NUM = AB.INS_NUM
			LEFT JOIN 	PWR_PRODUCT_HEADER H 
			ON 	R.PRICING_PRODUCT = H.PRODUCT_ID
			) PW
ON 	AB.INS_NUM=PW.INS_NUM
WHERE 	tsd.BAV_FLAG = 1 
and ab.input_date >= '2021-01-01 00:00:00'
AND 	ab.current_flag = 1 
AND ab.idx_group = '6'
AND 	ab.tran_type = 0 

AND (		
				(b.name not in ('COMM-BEACH-SWAP',
'COMM-BEACH-SWAP-HUB',
'COMM-CASH-FLOW',
'COMM-FUEL',
'COMM-NGL',
'COMM-PHYS-CRUDE',
'COMM-PHYS-IDX',
'COMM-PHYS-NGL',
'COMM-PHYS-TERMINAL',
'COMM-PRODUCTION',
'COMM-RETRO',
'GAS',
'GAS-FOR-NGL',
'GASGDA',
'GASPHYSBASIS',
'COMM-LOCATION-SWAP',
'COMM-PHYS',
'PWR-PHYS',
'COMM-PHYS-AGG',
'COMM-PHYS-AGG-TERMINAL',
'COMM-PHYS-BORROW',
'COMM-TIME-SWAP',
'GASIDX',
'RENEWABLE-PHYS'
))


AND
b.name not in (	'CASH',
'COMM-BAL-POSTING',
'COMM-BAL-POSTING-OFFSET',
'COMM-FEE',
'COMM-IMB',
'COMM-PAL',
'COMM-PAL-SETTLEMENT',
'COMM-PHYS-FEES',
'COMM-PHYS-TRANSPORT',
'COMM-STOR',
'COMM-TRANS',
'COMM-TRANSIT',
'COMM-TRANS-SETTLEMENT',
'PWR-FEE',
'RENEWABLE-INVENTORY',
'COMM-BAL-ACCTNG-IMPACT',
'COMM-BANKGAS-BAL-POSTING',
'COMM-IMBALANCE-CASHOUT',
'COMM-INV-NATGAS',
'COMM-IUK-INV-ADJ',
'COMM-NGL-VIRTUAL',
'COMM-PPA',
'COMM-STOR-BAL',
'COMM-TRANSIT-NGL',
'COMM-VIRTUAL-SWAP',
'LNG-MARGIN-XFER-DIV',
'LNG-MARGIN-XFER-EL',
'CAP-ENTRY',
'CAP-EXIT'
)
)